<a href="https://colab.research.google.com/github/seungsdew/-/blob/main/%EC%A0%84%EC%A0%84%EC%8B%AC%ED%99%94%EC%84%A4%EA%B3%84_%EA%B3%BC%EC%A0%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip3 install torch torchvision

In [9]:
import torch

In [12]:
a= torch.ones(4*4, dtype=torch.int32).reshape(4,4)
print(a)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [13]:
b = torch.arange(4*4, dtype = torch.int32).reshape(4,4)
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int32)

In [31]:
a.fill_(3)
a = torch.full((4, 4), 3, dtype=torch.int32)
a

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]], dtype=torch.int32)

In [ ]:
a = torch.arange((4,4), )

In [33]:
a = torch.randn(4*4)
b= torch.randn(4*4)
a


tensor([ 0.6731, -0.4567,  0.7521, -1.1213,  1.6967, -1.3411, -0.2564, -0.1762,
         0.3374, -0.5874, -1.8722, -0.9902,  0.8894,  0.0934,  0.0441,  0.0650])

In [34]:
b

tensor([-0.4447, -1.1157, -0.9338,  1.7561, -0.2663, -0.0793,  0.1112,  0.8202,
        -0.1484,  0.0343, -0.6766, -1.7354, -1.4806,  0.7130,  0.0287,  0.0881])

In [36]:
result = a+b
result

tensor([ 0.2284, -1.5725, -0.1817,  0.6349,  1.4304, -1.4204, -0.1452,  0.6440,
         0.1890, -0.5531, -2.5489, -2.7255, -0.5913,  0.8064,  0.0728,  0.1531])

In [38]:
a = torch.randn(2*2).reshape(2,2)
print(a)
a_inv = torch.inverse(a)
print(a_inv)

tensor([[ 0.5728,  0.5937],
        [ 1.4284, -0.4458]])
tensor([[ 0.4040,  0.5381],
        [ 1.2945, -0.5191]])


In [40]:
x = torch.randn(3,4)
print(x)
y = torch.ge(x, 0)
print(y)

tensor([[-0.5980, -0.5615,  1.1111,  0.1043],
        [ 0.4900, -0.8859, -0.2260,  1.1567],
        [-0.3907,  0.9773, -0.3562, -0.9517]])
tensor([[False, False,  True,  True],
        [ True, False, False,  True],
        [False,  True, False, False]])


In [55]:
x = torch.randn(1000)
print(x)
torch.max(x)
torch.argmax(x)

tensor([-6.5328e-01,  2.4985e+00,  1.7182e+00, -9.4446e-03, -1.3478e+00,
        -3.5835e-01, -4.3154e-01, -7.0099e-01,  1.5948e+00, -6.4049e-01,
         8.4888e-01,  1.0019e+00,  6.5917e-01,  9.1941e-01,  7.6393e-01,
        -7.7919e-01, -1.7198e+00, -7.1090e-01, -4.5676e-01,  1.0948e-01,
        -2.6480e+00, -1.4085e+00, -5.3088e-01, -1.7032e+00,  8.8772e-01,
        -1.4146e+00, -2.8756e-02, -5.6106e-01,  3.1801e-01, -1.7089e+00,
         5.1990e-01, -1.3045e-01,  1.1952e+00, -8.4066e-01, -4.1783e-02,
         1.6102e+00,  3.4387e-02, -2.5806e-01,  9.7328e-01, -1.6470e+00,
         1.3032e+00,  3.7498e-01, -2.7883e-01, -1.7775e+00, -2.0746e+00,
         2.4411e+00, -7.7228e-01, -1.7629e-01, -3.3182e-02,  5.4202e-03,
        -1.0470e+00, -1.5741e-01,  3.8446e-01, -1.8842e+00,  3.6903e-01,
        -2.5531e-01, -1.1515e+00, -1.6798e+00,  2.5823e-01,  7.3244e-01,
        -2.1509e+00,  3.6401e-01,  2.6842e-01,  1.2340e+00, -1.7736e-01,
         1.9178e+00, -5.4935e-01,  1.4160e+00, -4.5

IndexError: ignored

In [53]:
w =torch.randn(3,4)
v = torch.randn(4, 5)
result = torch.matmul(w, v)
print(w)
print(v)
print(result)

tensor([[-1.6015,  0.1189,  0.5328, -0.3757],
        [ 0.5927,  1.8251, -0.0942, -0.1918],
        [ 0.4319,  0.1154, -0.2564,  0.7343]])
tensor([[-2.2220, -1.8841,  0.5477,  0.0156, -1.1821],
        [ 0.2850, -0.1675,  1.4580,  0.0476, -1.2250],
        [-0.4000, -0.2433,  0.9037,  0.8785, -1.9075],
        [ 1.1609,  1.0826,  0.8612,  1.1828, -1.5093]])
tensor([[ 2.9432,  2.4611, -0.5459,  0.0045,  1.2981],
        [-0.9818, -1.6070,  2.7355, -0.2135, -2.4672],
        [ 0.0282,  0.0243,  0.8054,  0.6554, -1.2710]])


In [57]:
a = torch.arange(2*2, dtype=torch.int32)
print(a)
b = torch.arange(11,14, dtype= torch.int32)
print(b)
result = torch.cat((a, b))
print(result)

tensor([0, 1, 2, 3], dtype=torch.int32)
tensor([11, 12, 13], dtype=torch.int32)
tensor([ 0,  1,  2,  3, 11, 12, 13], dtype=torch.int32)


torch.cat(tensors, dim=0, out=None)
tensors: 연결할 텐서들의 시퀀스(리스트 등)입니다.
dim (옵션): 연결할 때 사용할 차원(축)을 지정합니다. 이 매개변수를 사용하여 연결할 차원을 선택할 수 있으며, 기본값은 0입니다.
out (옵션): 결과를 저장할 출력 텐서를 지정합니다. 이 매개변수를 사용하면 새로운 텐서를 생성하지 않고 결과를 저장할 수 있습니다.
예를 들어, 두 개의 텐서를 연결하려면 다음과 같이 사용할 수 있습니다:

torch.view는 모양만 바꿔주고 메모리는 똑같이 공유한다.
torch.shape는 모양만 바꿔주는 것이 아니라 메모리도 다른 공간에 할당되어 다른 텐서를 만들어 준다

>> x = torch.randn(2, 3, 5)
>>> x.size()
torch.Size([2, 3, 5])
>>> torch.permute(x, (2, 0, 1)).size()
torch.Size([5, 2, 3])
torch.permute는 차원의 순서를 서로 바꿔주고 기존의 tensor와 data를 공유한다.

torch.transpose는 2개의 차원을 transpose하고 기존의 tensor와 data를 공유한다
즉 데이터를 공유한다는 측면은 갖지만 연산방법과 계산할수 있는 차원의 수가 다르다.